spring.application.name=demoRefri
spring.datasource.url=jdbc:mysql://localhost:3306/zonarefri_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mercadopago.access.token=APP_USR-8639504829240881-061213-7d63fbf55999d0673fa9cb8e2c376c0b-2458733103
mercadopago.url.base=https://api.mercadopago.com/v1/payments/

ngrok.enabled=true
ngrok.authToken=2xh5oxz5hSJwN1GNvARJR3IBg3C_2yiPMCX236nnnqgeXC52Z

mercado.envios.api.url=https://api.mercadolibre.com/shipments


aws.s3.bucket-name=my-spring-boot-alex
aws.access-key=?Tu clave publica?
aws.secret-key=?Tu clave secreta?
aws.region=?Region de AWS?